# Generated by Django 2.1.3 on 2019-04-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdname', models.CharField(max_length=100, verbose_name='项目部门')),
            ],
            options={
                'verbose_name': '项目部门表',
                'verbose_name_plural': '项目部门表',
                'db_table': 'CustomerDep',
            },
        ),
        migrations.CreateModel(
            name='Customersess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40, verbose_name='客户姓名')),
                ('cphone', models.IntegerField(verbose_name='客户电话')),
                ('cdepname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.CustomerDep')),
            ],
            options={
                'verbose_name': '客户人员信息表',
                'verbose_name_plural': '客户人员信息表',
                'db_table': 'Customersess',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField(verbose_name='部门ID')),
                ('depname', models.CharField(max_length=20, verbose_name='部门名称')),
                ('dname', models.CharField(max_length=20, verbose_name='部门简称')),
                ('manager', models.CharField(max_length=20, verbose_name='部门经理')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '公司内部门',
                'verbose_name_plural': '公司内部门',
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Jobgrade',
            fields=[
                ('jobID', models.IntegerField(primary_key=True, serialize=False, verbose_name='岗位ID')),
                ('jjobgrade', models.CharField(max_length=40, verbose_name='岗位级别')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '岗位级别表',
                'verbose_name_plural': '岗位级别表',
                'db_table': 'jobgrade',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.IntegerField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('rrole', models.CharField(max_length=40, verbose_name='角色名称')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '角色层级表',
                'verbose_name_plural': '角色层级表',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='technicalGrade',
            fields=[
                ('tgid', models.IntegerField(primary_key=True, serialize=False, verbose_name='技术等级ID')),
                ('tgtechnicalgrade', models.CharField(max_length=40, verbose_name='技术等级')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '技术等级表',
                'verbose_name_plural': '技术等级表',
                'db_table': 'technicalgrade',
            },
        ),
        migrations.CreateModel(
            name='TGroup',
            fields=[
                ('trr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='组id')),
                ('parent_tg_id', models.IntegerField(verbose_name='父组id')),
                ('group_name', models.CharField(max_length=64, verbose_name='组名称')),
                ('gen_time', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('description', models.CharField(max_length=200, verbose_name='组描述')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '组表',
                'verbose_name_plural': '组表',
                'db_table': 'tgroup',
            },
        ),
        migrations.CreateModel(
            name='TGroupRightRelation',
            fields=[
                ('tgr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='记录标识')),
                ('right_type', models.CharField(choices=[(0, '可访问'), (1, '可授权')], default='可访问', max_length=32, verbose_name='权限类型')),
                ('isDelete', models.BooleanField(default=False)),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TGroup')),
            ],
            options={
                'verbose_name': '组权限表',
                'verbose_name_plural': '组权限表',
                'db_table': 'tgrouprightrelation',
            },
        ),
        migrations.CreateModel(
            name='TGroupRoleRelation',
            fields=[
                ('tgr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='记录标识')),
                ('isDelete', models.BooleanField(default=False)),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TGroup')),
            ],
            options={
                'verbose_name': '组角色表',
                'verbose_name_plural': '组角色表',
                'db_table': 'tgrouprolerelation',
            },
        ),
        migrations.CreateModel(
            name='TLog',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='日志id')),
                ('op_type', models.IntegerField(verbose_name='操作类型')),
                ('content', models.CharField(max_length=200, verbose_name='操作内容')),
                ('isDelete', models.BooleanField(default=False)),
                ('gen_time', models.DateField(auto_now=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志表',
                'verbose_name_plural': '操作日志表',
                'db_table': 'tlog',
            },
        ),
        migrations.CreateModel(
            name='TOrganization',
            fields=[
                ('to_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='组id')),
                ('parent_to_id', models.IntegerField(verbose_name='父组id')),
                ('org_name', models.CharField(max_length=64, verbose_name='组名称')),
                ('gen_time', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('description', models.CharField(max_length=200, verbose_name='组织描述')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '组织表',
                'verbose_name_plural': '组织表',
                'db_table': 'torganization',
            },
        ),
        migrations.CreateModel(
            name='TRight',
            fields=[
                ('tr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='权限id')),
                ('parent_tr_id', models.IntegerField(verbose_name='父权限')),
                ('right_name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('description', models.CharField(max_length=200, verbose_name='组织描述')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
                'db_table': 'tright',
            },
        ),
        migrations.CreateModel(
            name='TRole',
            fields=[
                ('tr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='角色id')),
                ('parent_tr_id', models.IntegerField(verbose_name='父级角色id')),
                ('role_name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('gen_time', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('description', models.CharField(max_length=200, verbose_name='组织描述')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'trole',
            },
        ),
        migrations.CreateModel(
            name='TRoleRightRelation',
            fields=[
                ('trr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='记录标识')),
                ('right_type', models.CharField(choices=[(0, '可访问'), (1, '可授权')], default='可访问', max_length=32, verbose_name='权限类型')),
                ('isDelete', models.BooleanField(default=False)),
                ('Role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TRole')),
                ('right_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TRight')),
            ],
            options={
                'verbose_name': '角色权限表',
                'verbose_name_plural': '角色权限表',
                'db_table': 'trolerightrelation',
            },
        ),
        migrations.CreateModel(
            name='TUserGroupRelation',
            fields=[
                ('tur_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='记录标识')),
                ('isDelete', models.BooleanField(default=False)),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TGroup')),
            ],
            options={
                'verbose_name': '用户组表',
                'verbose_name_plural': '用户组表',
                'db_table': 'tusergrouprelation',
            },
        ),
        migrations.CreateModel(
            name='TUserRightRelation',
            fields=[
                ('tur_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='记录标识')),
                ('right_type', models.CharField(choices=[(0, '可访问'), (1, '可授权')], default='可访问', max_length=32, verbose_name='权限类型')),
                ('isDelete', models.BooleanField(default=False)),
                ('tr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TRight')),
            ],
            options={
                'verbose_name': '用户权限表',
                'verbose_name_plural': '用户权限表',
                'db_table': 'tuserrightrelation',
            },
        ),
        migrations.CreateModel(
            name='TUserRoleRelation',
            fields=[
                ('tur_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='记录标识')),
                ('isDelete', models.BooleanField(default=False)),
                ('tr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TRole')),
            ],
            options={
                'verbose_name': '用户角色表',
                'verbose_name_plural': '用户角色表',
                'db_table': 'tuserrolerelation',
            },
        ),
        migrations.CreateModel(
            name='UnitName',
            fields=[
                ('dname', models.CharField(max_length=20, verbose_name='单位负责人')),
                ('unitname', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='单位名称')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '单位名称',
                'verbose_name_plural': '单位名称',
                'db_table': 'unitname',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uname', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='姓名')),
                ('upasswd', models.CharField(max_length=40, verbose_name='系统密码')),
                ('ugender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='男', max_length=32, null=True)),
                ('uCreatedate', models.DateField(auto_now_add=True, null=True, verbose_name='入职日期')),
                ('uupoto', models.ImageField(blank=True, null=True, upload_to='headportrait', verbose_name='照片')),
                ('uworkid', models.CharField(blank=True, max_length=100, null=True, verbose_name='工号')),
                ('uidcard', models.CharField(blank=True, max_length=100, null=True, verbose_name='身份证号码')),
                ('ubirthday', models.DateField(auto_now_add=True, null=True, verbose_name='出生年月日')),
                ('uphone', models.CharField(max_length=100, verbose_name='手机号码')),
                ('uemail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱地址')),
                ('ufirstcontact', models.CharField(blank=True, max_length=40, null=True, verbose_name='联系人姓名')),
                ('uconphone', models.CharField(blank=True, max_length=40, null=True, verbose_name='联系人号码')),
                ('uaddress', models.CharField(blank=True, max_length=200, null=True, verbose_name='现住址')),
                ('ueduschool', models.CharField(blank=True, max_length=100, null=True, verbose_name='毕业院校')),
                ('ueducation', models.CharField(blank=True, max_length=20, null=True, verbose_name='学历')),
                ('uorigin', models.CharField(blank=True, max_length=20, null=True, verbose_name='籍贯')),
                ('ulasttime', models.DateField(auto_now=True, verbose_name='最后修改日期')),
                ('isDelect', models.BooleanField(default=True)),
                ('utoken', models.CharField(max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
                ('reporttime', models.DateField(auto_now=True, null=True, verbose_name='报道日期')),
                ('manager', models.CharField(blank=True, max_length=40, null=True, verbose_name='上级姓名')),
                ('howyear', models.CharField(blank=True, choices=[('thisyear', '应届'), ('laseyear', '往届')], max_length=40, null=True)),
                ('jobgrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Jobgrade')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Role')),
                ('technicalgrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.technicalGrade')),
                ('udepname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Departments')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.UnitName')),
            ],
            options={
                'verbose_name': '员工表',
                'verbose_name_plural': '员工表',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='tuserrolerelation',
            name='tu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.AddField(
            model_name='tuserrightrelation',
            name='tu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.AddField(
            model_name='tusergrouprelation',
            name='tu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.AddField(
            model_name='tlog',
            name='tu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.AddField(
            model_name='tgrouprolerelation',
            name='tr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TRole'),
        ),
        migrations.AddField(
            model_name='tgrouprightrelation',
            name='tr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.TRight'),
        ),
        migrations.AddField(
            model_name='customersess',
            name='cprojectname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UnitName'),
        ),
        migrations.AddField(
            model_name='customerdep',
            name='dpname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UnitName'),
        ),
    ]
