# Generated by Django 2.1.3 on 2019-02-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='china_regionalTablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('parent', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'china',
            },
        ),
        migrations.CreateModel(
            name='CustomerDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdname', models.CharField(max_length=100, verbose_name='项目部门')),
            ],
            options={
                'verbose_name': '项目部门表',
                'verbose_name_plural': '项目部门表',
                'db_table': 'CustomerDep',
            },
        ),
        migrations.CreateModel(
            name='Customersess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40, verbose_name='客户姓名')),
                ('cphone', models.IntegerField(verbose_name='客户电话')),
                ('cdepname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.CustomerDep')),
            ],
            options={
                'verbose_name': '客户人员信息表',
                'verbose_name_plural': '客户人员信息表',
                'db_table': 'Customersess',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField(verbose_name='部门ID')),
                ('depname', models.CharField(max_length=20, verbose_name='部门名称')),
                ('dname', models.CharField(max_length=20, verbose_name='部门简称')),
                ('manager', models.CharField(max_length=20, verbose_name='部门经理')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '公司内部门',
                'verbose_name_plural': '公司内部门',
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Itfaulttpye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Itilworklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Itsla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalTime', models.CharField(max_length=20, verbose_name='完成时间')),
                ('wOrderNo', models.CharField(max_length=50, verbose_name='工单号')),
                ('process', models.CharField(max_length=200, verbose_name='处理过程')),
                ('wState', models.CharField(max_length=20, verbose_name='工单状态')),
                ('fHandler', models.CharField(max_length=20, verbose_name='流转处理人')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '处理过程',
                'verbose_name_plural': '处理过程',
                'db_table': 'Process',
            },
        ),
        migrations.CreateModel(
            name='UnitName',
            fields=[
                ('dname', models.CharField(max_length=20, verbose_name='单位负责人')),
                ('unitName', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='单位名称')),
                ('uname', models.CharField(max_length=10, verbose_name='单位简称')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '单位名称',
                'verbose_name_plural': '单位名称',
                'db_table': 'UnitName',
            },
        ),
        migrations.CreateModel(
            name='WorkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billingTime', models.CharField(max_length=20, verbose_name='开单时间')),
                ('workOrderNo', models.CharField(max_length=50, verbose_name='工单号')),
                ('unitName', models.CharField(max_length=20, verbose_name='单位名称')),
                ('clientName', models.CharField(max_length=20, verbose_name='客户姓名')),
                ('clientPho', models.CharField(max_length=50, verbose_name='客户电话')),
                ('clientAddress', models.CharField(max_length=100, verbose_name='客户位置')),
                ('faultClass', models.CharField(max_length=20, verbose_name='故障大类')),
                ('faultClasss', models.CharField(max_length=20, verbose_name='故障小类')),
                ('faultDetail', models.CharField(max_length=20, verbose_name='故障明细')),
                ('incidentCla', models.CharField(max_length=20, verbose_name='事件分类')),
                ('incidentRank', models.CharField(max_length=20, verbose_name='事件级别')),
                ('incidentState', models.CharField(max_length=20, verbose_name='事件状态')),
                ('incidentTheme', models.CharField(max_length=100, verbose_name='事件主题')),
                ('incidentDescribe', models.CharField(max_length=100, verbose_name='事件描述')),
                ('manageCourse', models.CharField(max_length=200, null=True, verbose_name='处理过程')),
                ('creator', models.CharField(max_length=20, verbose_name='创建人')),
                ('workState', models.CharField(max_length=20, verbose_name='工单状态')),
                ('flowHandler', models.CharField(max_length=20, null=True, verbose_name='流转处理人')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '工单系统',
                'verbose_name_plural': '工单系统',
                'db_table': 'WorkList',
            },
        ),
        migrations.AddField(
            model_name='customersess',
            name='cprojectname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UnitName'),
        ),
        migrations.AddField(
            model_name='customerdep',
            name='dpname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UnitName'),
        ),
    ]
