# Generated by Django 2.1.3 on 2019-03-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pactNo', models.CharField(max_length=20, verbose_name='合同编号')),
                ('projectname', models.CharField(max_length=40, verbose_name='项目名称')),
                ('signedname', models.CharField(max_length=40, verbose_name='签约名称')),
                ('signedsubject', models.CharField(max_length=40, verbose_name='签约主体')),
                ('billingunit', models.CharField(max_length=40, verbose_name='开票单位')),
                ('executedate', models.CharField(max_length=20, verbose_name='执行日期')),
                ('begindate', models.CharField(max_length=20, verbose_name='开始日期')),
                ('overdate', models.CharField(max_length=20, verbose_name='结束日期')),
                ('pacttotalsum', models.CharField(max_length=20, verbose_name='合同总额')),
                ('monthlyfee', models.CharField(max_length=20, verbose_name='月均费用')),
                ('Agreedpaymenttime', models.CharField(blank=True, max_length=20, null=True, verbose_name='约定付款时间')),
                ('knotrate', models.CharField(max_length=20, verbose_name='结费方式')),
                ('accountmanager', models.CharField(max_length=20, verbose_name='客户负责人')),
                ('projectaddress', models.CharField(max_length=40, verbose_name='项目地址')),
                ('followuppeople', models.CharField(max_length=20, verbose_name='项目跟进人')),
                ('servertype', models.CharField(blank=True, max_length=40, null=True, verbose_name='服务类型')),
                ('servicemode', models.CharField(max_length=20, verbose_name='服务方式')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '商务合同',
                'verbose_name_plural': '商务合同',
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pactNo', models.CharField(max_length=20, verbose_name='合同编号')),
                ('file', models.FileField(max_length=255, upload_to='contractfile')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '合同附带文件',
                'verbose_name_plural': '合同附带文件',
                'db_table': 'files',
            },
        ),
    ]
